<a href="https://colab.research.google.com/github/prithwi3/Machine-Learning/blob/main/ML6(NUMPY).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b = np.array([[1,2,3], [0.3,0.4,0.5]])
print(b)

[[1.  2.  3. ]
 [0.3 0.4 0.5]]


In [5]:
# get dimension

a.ndim

1

In [6]:
b.ndim

2

In [7]:
# get shape
a.shape

(3,)

In [8]:
b.shape

(2, 3)

In [9]:
# get type
a.dtype

dtype('int64')

In [10]:
a.itemsize

8

In [11]:
# get total number of size
#n.shape * n.itemsize = (3*8)
a.nbytes

24

In [12]:
c = np.array([[1,2,3,4,5,6,7],[3,4,5,6,7,8,9]])
print(c)

[[1 2 3 4 5 6 7]
 [3 4 5 6 7 8 9]]


In [13]:
c.shape

(2, 7)

In [14]:
# get a specific element (r,c)

c[1,5]

8

In [15]:
# get a specific row
c[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
# get  specific column
c[:,1]

array([2, 4])

In [17]:
# getting a lil more fancy(starting index : end index : step size)
c[0, 1:7:2] #or, c[0, 1:-1:2]

array([2, 4, 6])

In [18]:
#change element
c[1,5] = 20
print(c)

[[ 1  2  3  4  5  6  7]
 [ 3  4  5  6  7 20  9]]


In [19]:
c[:,2] = 13
print(c)

[[ 1  2 13  4  5  6  7]
 [ 3  4 13  6  7 20  9]]


In [20]:
c[:,1] = [9,10]
print(c)

[[ 1  9 13  4  5  6  7]
 [ 3 10 13  6  7 20  9]]


In [21]:
d = np.array([[[1,2],[2,4]],[[3,4],[4,5]]])
print(d)

[[[1 2]
  [2 4]]

 [[3 4]
  [4 5]]]


In [22]:
# get a specific value
d[0,1,1]

4

In [23]:
d[:,1,:]

array([[2, 4],
       [4, 5]])

In [24]:
d[:,0,:] = [[9,9],[8,8]]
print(d)

[[[9 9]
  [2 4]]

 [[8 8]
  [4 5]]]


In [25]:
#All Zero's matrix
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [26]:
#All is 1 matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [27]:
np.ones((4,2,2), dtype='int16') #or, we can use dtype=32

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int16)

In [28]:
#any other number
np.full((2,2,2),99)

array([[[99, 99],
        [99, 99]],

       [[99, 99],
        [99, 99]]])

In [29]:
#random decimal numbers
np.random.rand(4,2)

array([[0.51829873, 0.40038446],
       [0.6709742 , 0.71899655],
       [0.49498394, 0.70617596],
       [0.69725732, 0.23671497]])

In [30]:
np.random.rand(4,2,2)

array([[[0.31656586, 0.98279397],
        [0.9890149 , 0.24614765]],

       [[0.27508299, 0.39917801],
        [0.00904675, 0.07882142]],

       [[0.2573474 , 0.32209032],
        [0.45898173, 0.37301963]],

       [[0.32347518, 0.39077075],
        [0.33029347, 0.60327018]]])

In [31]:
#random integer number
np.random.randint(3,7,size=(3,3))

array([[3, 6, 3],
       [6, 3, 3],
       [6, 6, 5]])

In [32]:
#identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
#repeat array element
arr = np.array([[1,2,3]])
r1= np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [34]:
arr = np.array([[1,2,3]])
r1= np.repeat(arr,3,axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [35]:
#A complicated matrix

output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [36]:
#copy
a = np.array([1,2,3])
b=a.copy()
b[0] = 100
print(a)

[1 2 3]


In [37]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [38]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [39]:
#array multiply when mismatch dimensions

a = np.ones((2,3))
print(a)

b= np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [40]:
#Find the determinant

c= np.identity(3)
np.linalg.det(c)

1.0

In [41]:
#statistics

stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
np.min(stats)

1

In [83]:
np.max(stats)

6

In [43]:
#Reorganizing
before = np.array([[1,2,3,4],[4,5,6,7]])
print(before)

after = before.reshape(4,2)
print(after)

[[1 2 3 4]
 [4 5 6 7]]
[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [44]:
#vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([4,5,6,7])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [1, 2, 3, 4],
       [4, 5, 6, 7]])

In [49]:
#horizontal stack
h1 = np.array([1,2,3])
h2 = np.array([4,5,6])
np.hstack([h1,h1,h2,h2]) #or, np.hstack((h1,h1,h2,h2))

array([1, 2, 3, 1, 2, 3, 4, 5, 6, 4, 5, 6])

In [50]:
#list in a numpy
a = np.array([1,2,3,4,5,6,7])
a[[0,1,3]]

array([1, 2, 4])